services:
    KatenaChain\ClientBundle\Services\Transactor:
        class: KatenaChain\ClientBundle\Services\Transactor
        tags: ['katena-chain']
        arguments:
            $apiUrl: '%kc_client.api.url%'
            $chainId: '%kc_client.chain.chain_id%'
            $signerCompanyBcId: '%kc_client.chain.signer_company_bcid%'
            $signerId: '%kc_client.chain.signer_id%'
            $signerPrivateKeyBase64: '%kc_client.chain.signer_private_key%'

    kc_client.transactor:
        alias: KatenaChain\ClientBundle\Services\Transactor
