services:
    KatenaChain\ClientBundle\Services\Transactor:
        class: KatenaChain\ClientBundle\Services\Transactor
        tags: ['katena-chain']
        arguments:
            $apiUrl: '%kc_client.api.url%'
            $chainId: '%kc_client.chain.chain_id%'
            $companyBcid: '%kc_client.chain.company_bcid%'
            $privateKeyBase64: '%kc_client.chain.private_key%'

    kc_client.transactor:
        alias: KatenaChain\ClientBundle\Services\Transactor
